# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab20248ba6d16af5c63bae754b5c0df77b84e5af1f8a54043806dad1765efb662258ebd9f3767b98020c30a5090953bced51a6f4733edacc465ccfe8abd1b226

test:
  secret_key_base: 2f0bc07d02fa9fd4861c0d0f2eb6928d5e0c3d8b16d86ca154c26c7bd75bd83ed0273dd82b6b791e2c40aab98d03a4fbe38a130f1ff455c4b76a810bc5f15880

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
